spring.application.name=med-backend
# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3307/med_backend?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, validate, update) ( note: for production update isn't recommended to use)
spring.jpa.hibernate.ddl-auto = update
# show sql query logs
spring.jpa.show-sql= true
logging.level.org.hibernate=warn
jwt.secret=your_super_long_secret_key_change_me_676767676

